### ISSUE TITLE
Add support for Apertium analysers

### ISSUE THREAD

**Issue by ftyers** [conllul/dockerimage#1]
Many of them have ready mapping files for Apertium POS/Feats → UD POS/Feats and were used in the production of the given treebanks. E.g. for Kazakh:

https://github.com/apertium/apertium-kaz/blob/master/apertium-kaz.kaz.udx

For Breton:

https://github.com/apertium/apertium-bre/blob/master/apertium-bre.bre.udx

For Kurdish:

https://github.com/apertium/apertium-kmr/blob/master/apertium-kmr.kmr.udx

Please let me know if you have any questions about the structure of the repos or how to use them. There are Apertium analysers for approximately 60-70% of the current UD treebanks. Also if it's possible, please cite the relevant papers on each of the analysers, or the main Apertium paper.  :)

**Comment by habeanf** [comment]
The CoNLL-UL set of resources, as well as the docker image, contain a converted set of Apertium lexicons. We indeed [provide the Kazakh](https://github.com/conllul/UL_Kazakh-KTB/blob/master/UDLex_Kazakh-ApertiumMA.conllul.bz2) Apertium-based lexicon and [.conllul analyses of respective treebank files](https://github.com/conllul/UL_Kazakh-KTB). I'm not sure about the Kurdish lexicon, but the Breton treebank did not participate in the 2018 Shared Task - at least not as one with a training/dev set.

In our paper we cite [Sagot (2018)](http://www.lrec-conf.org/proceedings/lrec2018/pdf/705.pdf) which details the conversion process.

If you feel there are missing resources, you are welcome to provide a pull request that adds them

**Comment by ftyers** [comment]
[Breton participated](http://universaldependencies.org/conll18/results-las.html#br_keb) :) I will send an email offline about the other stuff. Thanks!

**Comment by habeanf** [comment]
As I've said, [not with a training/dev set](https://github.com/UniversalDependencies/UD_Breton-KEB) (no train or dev set files). Without a training/dev set, there is no model to induce.

We will soon provide .conllul files for test files too, but we would not have been able to provide them to the participating teams since .conllul files would reveal gold sentence segmentation and tokenization.

**Comment by ftyers** [comment]
Do you need to? You can generate a full-form lexicon using the dictionary. Like this:
```
$ lt-expand apertium-bre.bre.dix  | grep -v ':<:' | sed 's/:>:/:/g' | python3 ~/source/ud-scripts/conllu-feats-apertium2ud.py apertium-bre.bre.udx 
...
ra	ra	PART	vpart	Mood=Opt
na	na	PART	vpart	Polarity=Neg
en em	en em	PART	vpart	Reflex=Yes
en ur	en ur	PART	vpart	_
me	prpers	PRON	prn	Case=Nom|Number=Sing|Person=1|PronType=Prs
te	prpers	PRON	prn	Case=Nom|Number=Sing|Person=2|PronType=Prs
eñ	prpers	PRON	prn	Case=Nom|Gender=Masc|Number=Sing|Person=3|PronType=Prs
hi	prpers	PRON	prn	Case=Nom|Gender=Fem|Number=Sing|Person=3|PronType=Prs
ni	prpers	PRON	prn	Case=Nom|Number=Plur|Person=1|PronType=Prs
c’hwi	prpers	PRON	prn	Case=Nom|Number=Plur|Person=2|PronType=Prs
...
```

There are a fair number of forms, although you probably want to exclude the ones with `#` in.
```
$ lt-expand apertium-bre.bre.dix  | grep -v ':<:' | sed 's/:>:/:/g' | python3 ~/source/ud-scripts/conllu-feats-apertium2ud.py apertium-bre.bre.udx |wc -l
567089
```

Where `conllu-feats-apertium2ud.py` is found [here](https://github.com/ftyers/ud-scripts).

**Comment by habeanf** [comment]
> Do you need to?

.. towards what end? The purpose of CoNLL-UL is to provide complementing morphological analyses for UD treebanks. For UD v2.2 data provided for the shared task there were no treebank files for Breton, therefore we did not provide .conllul files. Now that the test files are released, we can add treebanks with only test data as well as their lexicons and analyzers.

**Comment by ftyers** [comment]
The UD_Breton treebank has been created from the output of the morphological analyser. So any analysis in the treebank will also be in the morphological analyser. I perhaps don't understand the objectives of the project so well, but if you want to create morphological models that have the same tagset/tokenisation as the treebank, then a good way to do it for Breton would be to use the lexicon in `apertium-bre`. But perhaps I have misunderstood.

**Comment by dseddah** [comment]
Hi Francis,
there's two things: the whole project itself, promoting the use of ambiguous morphological analysis input for UD parsing and its shared task incarnation, only using the data at our disposal to provide analysis. For breton, the thing is that without any data, we could only have provided the whole lexicon as it, not the one under our format which is basically the intersection between a lexicon/morphological analyser and a finite state automaton representing the input sentence. Since we didn't have nothing for Breton until the test raw data was released, we had nothing to intersect so to speak and more importantly, no right to disclose additional data for the shared task.

Regarding, the missing ref in the Moore et al, 2018 paper. it's our bad, the reference were there but not included for some now irrelevant editing reasons. We'll update the paper of course in the lrec proceedings if that's still possible and/or will release an updated version on arXiv. Sorry about this. 

Best,
Djamé

**Comment by ftyers** [comment]
@dseddah ah ok, now I understand! I hadn't got the "shared task"-only part! Thanks for the offer, if it's possible great, if not, no problem. We should make ourselves more visible! This is a great project!
